name: Build Kernel for Redmi Note 14 5G

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v3
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: beryl-u-oss
          path: kernel

      - name: Set up Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache clang curl flex git libssl-dev libncurses-dev lld python3 unzip zstd

      - name: Download Clang Toolchain
        run: |
          mkdir -p ~/toolchains
          cd ~/toolchains
          git clone https://github.com/ClangBuiltLinux/google-clang.git clang

      - name: Configure Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER=github
          export KBUILD_BUILD_HOST=actions
          export CLANG_PATH=~/toolchains/clang
          export PATH=$CLANG_PATH/bin:$PATH
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export CC=clang
          cd kernel
          make O=out beryl_defconfig

      - name: Build Kernel
        run: |
          cd kernel
          make -j$(nproc) O=out

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: boot_custom.img
          path: kernel/out/arch/arm64/boot/Image.gz-dtb
